### ISSUE TITLE
Issue: Legull doesn't conform with Wordpress date format

### ISSUE THREAD

**Issue by eggplantUK** [codearachnid/legull#13]
The date format used in the Terms ignores the date format set in the Wordpress settings.

More detail here: https://wordpress.org/support/topic/date-doesnt-conform-with-wordpress-format

**Comment by codearachnid** [comment]
I agree with the annoyance. I had anticipated enabling a way to filter the date; however, I have found from experience most general users don't pay attention to the date format or format it in such a way that would be detrimental to the display of the date on the legal terms. I do think for a future release I will enable a filterable override - but as you suggest revert to using the format defined by WordPress.
