### ISSUE TITLE
Does not publish the TOS or Privacy Policy pages

### ISSUE THREAD

**Issue by BrentNewland** [codearachnid/legull#19]
Plugins:
All In One WP Security
Autoptimize
CloudFlare
Coupon Creator
CSS Plus
Enable Media Replace
Extra Posts Pages Menu
Footer Putter
Google Analytics Dashboard for WP
jonradio Multiple Themes
Legull
Max Mega Menu
No Slug Conflicts With Trash
OS Integration
Page Links To
Plugin Organizer
Quick Business Website
Simple History
Simple Staff List
TablePress Extension: Responsive Tables
TablePress
Trashed By
UpdraftPlus - Backup/Restore
Wordfence Security
WordPress phpinfo()
WordPress SEO
WP Disable Comments
WP-Optimize
WP-ServerInfo

I click Publish Page, and no pages are made. After it failed, I tried creating pages at /legal/privacy-policy/ and /legal/terms-of-service/ and publishing, but it didn't change those pages either. From the Legull>Terms page, I can click on each one and see the editor, but clicking Update does nothing. I get a 404 page.

**Comment by codearachnid** [comment]
Hey @BrentNewland this is actually on our radar and has been fixed. We have a few more exiting items coming in our next release as well. Unfortuantly, I am a bit delayed in getting the release out the door so you are still seeing this bug. A quick fix is after publishing to go to your site Settings > permalinks and then clicking save. Please note you only have to do this once as the settings will persist.
