### ISSUE TITLE
Plugin Abandoned?

### ISSUE THREAD

**Issue by gmwash** [codearachnid/legull#20]
Reading the Details page on Wordpress, you say this plugin is "actively supported". However, it appears it hasn't been updated for a year. That means having it on my site very likely creates a vulnerable "back door" (https://www.wordfence.com/blog/2016/03/attackers-gain-access-wordpress-sites/).  

Do you plan to leave the plugin abandoned, or will you resume "active support"? 

I thought this plugin was such a wonderful find. Hate the idea of having to remove it from my sites, and advise my clients to do the same. Safety first, after all.

**Comment by codearachnid** [comment]
The plugin has not been abandoned. We have a release underway but with other priorities in the way getting it out the door was delayed over the past year. As far as addressing security vulnerabilities the article you linked to does address defined weaknesses that plugins can introduce. We have done extensive security testing of the Legull plugin and as such it is secure to date. An update just to keep the updated date freshness does not improve the security.

I think you will like the new improvements that are coming with the integration with other plugins (form builders and ecommerce). Thank you.

**Comment by gmwash** [comment]
Thanks so much for responding so quickly! I appreciate all you've said, and look forward to the improvements. 

And, while an "update just to keep the updated date" fresh doesn't improve security (which isn't my expectation), it does provide peace of mind, both to those considering your plugin anew, and to those like me who already have it installed, and are concerned with ensuring we've taken every precaution we can to secure our website, including removing "apparently" abandoned plugins. 

Only **you** have the inside scoop on what's going on with your plugin. But, you can help in a tremendous way those of us who depend on it by keeping that date fresh if all is well in the meantime. :)

Thanks again for your wonderful plugin and speedy response.

**Comment by codearachnid** [comment]
I definitively see your perspective of freshness gives feeling of upkeep and agree that it does help boost confidence. Will be looking to improve our support procedures going forward to help with this as well.
